import { useEffect, useState } from "react";
import { PriceRow } from "client/lib/hooks/calculation/benchmark";

/**
 * Static daily-close history for VOO (the S&P 500 ETF proxy), fetched once
 * and shared across every component that needs an index price. Generated by
 * `scripts/fetch-voo-history.ts` from Yahoo and committed at
 * `src/client/public/static-data/`. The CSV has columns
 * `date,close,close_adjusted` — we use the unadjusted `close` column so the
 * benchmark math matches Plaid's institutional `close_price` convention (the
 * same number `valueAt` uses for the user's holdings).
 *
 * The fetch is memoized on a module-level promise so multiple mounted
 * consumers (PerformanceBenchmark + HoldingsComposition) share one request.
 */
const VOO_HISTORY_URL = "/static-data/voo_price_history.csv";

let vooHistoryPromise: Promise<PriceRow[]> | null = null;

export const loadVooHistory = (): Promise<PriceRow[]> => {
  if (!vooHistoryPromise) {
    vooHistoryPromise = fetch(VOO_HISTORY_URL)
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(`${r.status}`))))
      .then((text) => {
        const lines = text.trim().split("\n");
        const rows: PriceRow[] = [];
        // Skip header. Each row: date,close,close_adjusted
        for (let i = 1; i < lines.length; i++) {
          const parts = lines[i].split(",");
          const date = parts[0];
          const close = Number(parts[1]);
          if (date && Number.isFinite(close)) rows.push({ date, close });
        }
        rows.sort((a, b) => (a.date < b.date ? -1 : 1));
        return rows;
      })
      .catch((err) => {
        // Reset so future mounts can retry (e.g. after a transient network
        // blip). The catch keeps consumers from crashing — the benchmark
        // just renders empty until the data lands.
        vooHistoryPromise = null;
        console.warn("Failed to load VOO price history", err);
        return [];
      });
  }
  return vooHistoryPromise;
};

/**
 * Load the shared VOO daily-close history. Returns null until the data
 * lands, then the date-sorted price rows (empty array on persistent
 * failure).
 */
export const useVooHistory = (): PriceRow[] | null => {
  const [vooHistory, setVooHistory] = useState<PriceRow[] | null>(null);
  useEffect(() => {
    let alive = true;
    loadVooHistory().then((rows) => {
      if (alive) setVooHistory(rows);
    });
    return () => {
      alive = false;
    };
  }, []);
  return vooHistory;
};
