name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [main]

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    outputs:
      secrets-exist: ${{ steps.check-secrets-step.outputs.defined }}
    steps:
      - name: Check for Secret availability
        id: check-secrets-step
        shell: bash
        run: |
          if [[ '${{ secrets.DOCKER_HUB_USERNAME }}' != '' && '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}' != '' && '${{ secrets.DEPLOY_URL }}' != '' && '${{ secrets.DEPLOY_SECRET }}' != '' ]]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  docker-push:
    needs: check-secrets
    runs-on: ubuntu-latest
    if: needs.check-secrets.outputs.secrets-exist == 'true'

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Get short SHA
        id: sha
        run: echo "short=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/budget:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/budget:sha-${{ steps.sha.outputs.short }}

  deploy:
    needs: [check-secrets, docker-push]
    runs-on: ubuntu-latest
    if: needs.check-secrets.outputs.secrets-exist == 'true'
    steps:
      - name: Trigger deploy
        run: |
          curl -X POST ${{ secrets.DEPLOY_URL }} -H "Content-Type: application/json" -d '{"secret": "${{ secrets.DEPLOY_SECRET }}"}'
