import { useEffect, useMemo, useState } from "react";
import { Account, useAppContext } from "client";
import {
  extractCashFlows,
  computeMWR,
  computeBenchmarkTWR,
  valueAt,
  buildPriceAt,
  earliestDataDate,
} from "client/lib/hooks/calculation/benchmark";
import "./index.css";

interface Props {
  account: Account;
}

type WindowKey = "1Y" | "3Y" | "All";
const WINDOW_OPTIONS: WindowKey[] = ["1Y", "3Y", "All"];
const BENCHMARK_TICKER = "VOO";

// Static daily-close history for VOO, fetched once and shared across all
// PerformanceBenchmark instances. Generated by `scripts/fetch-voo-history.ts`
// from Yahoo and committed at `src/client/public/static-data/`. The CSV
// has columns `date,close,close_adjusted` — we use the unadjusted column
// so the benchmark TWR matches Plaid's institutional `close_price`
// convention (the same number `valueAt` uses for the user's holdings).
const VOO_HISTORY_URL = "/static-data/voo_price_history.csv";
interface PriceRow {
  date: string;
  close: number;
}
let vooHistoryPromise: Promise<PriceRow[]> | null = null;
const loadVooHistory = (): Promise<PriceRow[]> => {
  if (!vooHistoryPromise) {
    vooHistoryPromise = fetch(VOO_HISTORY_URL)
      .then((r) => (r.ok ? r.text() : Promise.reject(new Error(`${r.status}`))))
      .then((text) => {
        const lines = text.trim().split("\n");
        const rows: PriceRow[] = [];
        // Skip header. Each row: date,close,close_adjusted
        for (let i = 1; i < lines.length; i++) {
          const parts = lines[i].split(",");
          const date = parts[0];
          const close = Number(parts[1]);
          if (date && Number.isFinite(close)) rows.push({ date, close });
        }
        rows.sort((a, b) => (a.date < b.date ? -1 : 1));
        return rows;
      })
      .catch((err) => {
        // Reset so future widget mounts can retry (e.g. after a transient
        // network blip). The catch keeps the widget from crashing — the
        // benchmark row just renders empty until the data lands.
        vooHistoryPromise = null;
        console.warn("Failed to load VOO price history", err);
        return [];
      });
  }
  return vooHistoryPromise;
};

const toDateString = (d: Date) => d.toISOString().slice(0, 10);

const formatPct = (n: number | null): string => {
  if (n === null || !Number.isFinite(n)) return "—";
  return `${n >= 0 ? "+" : ""}${(n * 100).toFixed(2)}%`;
};

// Walk a sorted price series for the latest close ≤ `date`. Mirrors
// the `priceAt` behavior in benchmark.ts for the user's snapshots.
const priceAtIn = (history: PriceRow[], date: string): number | null => {
  if (history.length === 0) return null;
  let best: number | null = null;
  for (const r of history) {
    if (r.date <= date) best = r.close;
    else break;
  }
  return best;
};

export const PerformanceBenchmark = ({ account }: Props) => {
  const { account_id } = account;
  const { data, viewDate } = useAppContext();
  const { investmentTransactions, holdingSnapshots, securitySnapshots } = data;

  const [windowKey, setWindowKey] = useState<WindowKey>("1Y");
  const [vooHistory, setVooHistory] = useState<PriceRow[] | null>(null);

  useEffect(() => {
    let alive = true;
    loadVooHistory().then((rows) => {
      if (alive) setVooHistory(rows);
    });
    return () => {
      alive = false;
    };
  }, []);

  const computed = useMemo(() => {
    // "Earliest available data" is `min(first_holding_snapshot, first_txn)`
    // for the account. Accounts whose txn history predates the snapshot
    // history can show a longer "All" window via the txn-derived qty walk
    // in valueAt.
    const earliest = earliestDataDate({
      accountId: account_id,
      holdingSnapshots,
      investmentTransactions,
    });
    if (!earliest) return null;

    // windowEnd follows viewDate (end of the period the user is looking at),
    // capped at today since we have no future data. Same convention as
    // HoldingsComposition's `viewEndDate`.
    const today = new Date();
    const viewEnd = viewDate.getEndDate();
    const effectiveEnd = viewEnd > today ? today : viewEnd;
    const windowEnd = toDateString(effectiveEnd);
    const clampStart = (target: Date): { value: string; clamped: boolean } => {
      const t = toDateString(target);
      return t < earliest! ? { value: earliest!, clamped: true } : { value: t, clamped: false };
    };

    let windowStart: string;
    let isClamped = false;
    if (windowKey === "All") {
      windowStart = earliest;
    } else {
      const years = windowKey === "1Y" ? 1 : 3;
      const target = new Date(effectiveEnd);
      target.setFullYear(target.getFullYear() - years);
      const r = clampStart(target);
      windowStart = r.value;
      isClamped = r.clamped;
    }

    if (windowEnd <= windowStart) return null;

    const priceAt = buildPriceAt(securitySnapshots);
    const vStart = valueAt({
      date: windowStart,
      windowStart,
      accountId: account_id,
      holdingSnapshots,
      investmentTransactions,
      priceAt,
    });
    const vEnd = valueAt({
      date: windowEnd,
      windowStart,
      accountId: account_id,
      holdingSnapshots,
      investmentTransactions,
      priceAt,
    });

    const allFlows = extractCashFlows(investmentTransactions, holdingSnapshots, account_id);
    const flows = allFlows.filter((f) => f.date > windowStart && f.date <= windowEnd);

    const mwr = computeMWR({ flows, vStart, vEnd, windowStart, windowEnd });

    // Benchmark TWR over the user's full chosen window. VOO close prices
    // come from the static CSV (covers 2010-09 → today), so we never
    // narrow the comparison window.
    let benchmark: ReturnType<typeof computeBenchmarkTWR> | null = null;
    if (vooHistory && vooHistory.length > 0) {
      const priceStart = priceAtIn(vooHistory, windowStart);
      const priceEnd = priceAtIn(vooHistory, windowEnd);
      if (priceStart && priceEnd) {
        benchmark = computeBenchmarkTWR({ priceStart, priceEnd, windowStart, windowEnd });
      }
    }

    const yearsInWindow =
      (new Date(windowEnd).getTime() - new Date(windowStart).getTime()) / (1000 * 60 * 60 * 24 * 365);
    const suppressAnnualized = yearsInWindow < 0.5;

    const gap =
      mwr.annualized !== null && benchmark ? mwr.annualized - benchmark.annualized : null;

    return {
      windowStart,
      windowEnd,
      vStart,
      vEnd,
      flowCount: flows.length,
      mwr,
      benchmark,
      gap,
      suppressAnnualized,
      isClamped,
    };
  }, [
    account_id,
    investmentTransactions,
    holdingSnapshots,
    securitySnapshots,
    windowKey,
    viewDate,
    vooHistory,
  ]);

  if (!computed) return null;
  const { windowStart, windowEnd, mwr, benchmark, gap, suppressAnnualized, isClamped } = computed;

  return (
    <>
      <div className="propertyLabel">Investment&nbsp;Performance</div>
      <div className="property performanceBenchmark">
        <div className="performanceWindowPicker">
          {WINDOW_OPTIONS.map((opt) => (
            <button
              key={opt}
              type="button"
              className={opt === windowKey ? "active" : ""}
              onClick={() => setWindowKey(opt)}
            >
              {opt}
            </button>
          ))}
        </div>

        <div className="performanceRow">
          <span className="performanceLabel">Your asset return (MWR)</span>
          <span className="performanceValues">
            {mwr.status === "ok" ? (
              <>
                <span className="cum">{formatPct(mwr.cumulative)}</span>
                {!suppressAnnualized && (
                  <span className="ann">{formatPct(mwr.annualized)}/yr</span>
                )}
              </>
            ) : (
              <span className="no-data">—</span>
            )}
          </span>
        </div>

        <div className="performanceRow">
          <span className="performanceLabel">{BENCHMARK_TICKER} benchmark</span>
          <span className="performanceValues">
            {benchmark ? (
              <>
                <span className="cum">{formatPct(benchmark.cumulative)}</span>
                {!suppressAnnualized && (
                  <span className="ann">{formatPct(benchmark.annualized)}/yr</span>
                )}
              </>
            ) : (
              <span className="no-data">{vooHistory ? "no price data" : "loading…"}</span>
            )}
          </span>
        </div>

        {gap !== null && !suppressAnnualized && (
          <div className="performanceRow gap">
            <span className="performanceLabel">vs benchmark</span>
            <span className={`performanceValues ${gap >= 0 ? "positive" : "negative"}`}>
              <span className="ann">{formatPct(gap)}/yr</span>
            </span>
          </div>
        )}

        <div className="performanceFootnote">
          Showing {windowStart} → {windowEnd} · asset positions only (cash excluded)
          {isClamped && " · clamped to earliest data"}
          {suppressAnnualized && " · annualized hidden (window <6mo)"}
        </div>
      </div>
    </>
  );
};
